---
- name: L2-EVPN-CONFIG
  hosts: leaf
  connection: local
  gather_facts: no

  vars_files:
    - L2.yml
  vars:
    cli:
      username: admin
      password: cisco
      host: 192.168.127.11
      transport: cli

  tasks:
    - name: CREATE VLAN AND MAP VNI
      cisco.nxos.nxos_vlans:
        config:
          - vlan_id: "{{ item.vlan_id }}"
            mapped_vni: "{{ item.vni }}"
            name: "{{ item.name }}"
      with_items: "{{ vlan_11 }}"
                 
 
